# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Youva Gaud√© | Game Programmer Portfolio
email: ygaude@student.42.fr

description: I like to make games.


baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.youva.fr" # the base hostname & protocol for your site
twitter_username: youvadidj
github_username:  Eviber

# Build settings
markdown: kramdown
